# Generated by Django 4.2.3 on 2023-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(max_length=200),
        ),
    ]
